name: Build Executables

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            ffmpeg_url: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
            ffmpeg_name: ffmpeg.exe
          - os: macos-latest
            ffmpeg_url: https://evermeet.cx/ffmpeg/ffmpeg-6.1.zip
            ffmpeg_name: ffmpeg

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Download and setup FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ matrix.ffmpeg_url }} -OutFile ffmpeg.zip
        Expand-Archive -Path ffmpeg.zip -DestinationPath .
        Move-Item -Path "ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe" -Destination .
    
    - name: Download and setup FFmpeg (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        curl -L ${{ matrix.ffmpeg_url }} -o ffmpeg.zip
        unzip ffmpeg.zip
        chmod +x ffmpeg
    
    - name: Build executable
      run: python build.py
    
    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Youtify-Windows
        path: dist/Youtify/Youtify.exe
    
    - name: Upload macOS artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Youtify-macOS
        path: dist/Youtify/Youtify 